name: Run Pytest Tests

on:
  push:     # jeder Push, egal welcher Branch
  pull_request:  # jeder PR, egal von/zu welchem Branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: |
          pytest
